[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["/opt/venv/bin/python manage.py collectstatic --noinput"]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
