# Generated by Django 5.2.7 on 2025-10-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_units_and_tokencode'),
        ('transactions', '0002_initial'),
    ]

    operations = [
    ]
