# Generated by Django 5.2.7 on 2025-10-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_tokenpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='last_top_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
