# Generated by Django 5.2.7 on 2025-10-10 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_add_units_and_manualrecharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecharge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_recharges', to=settings.AUTH_USER_MODEL),
        ),
    ]
