# Generated by Django 5.2.7 on 2025-10-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_add_tokenpool_amount'),
        ('meters', '0007_alter_manualrecharge_user'),
    ]

    operations = [
    ]
