# Generated by Django 5.2.7 on 2025-10-15 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_merge_20251010_1129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRechargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('default_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_payment_method', models.CharField(blank=True, max_length=100)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('apply_to_all', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recharge_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoRechargeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_recharge_events', to='meters.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recharge_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
