# Generated by Django 5.2.7 on 2025-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meter_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
