# Generated by Django 5.2.7 on 2025-10-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meter_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
